"""add_is_pending_to_membership

Revision ID: 25002cf151ed
Revises: a69831e0be46
Create Date: 2026-06-25 06:04:48.322804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "25002cf151ed"
down_revision: Union[str, Sequence[str], None] = "a69831e0be46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_memberships",
        sa.Column(
            "is_pending", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_memberships", "is_pending")
    # ### end Alembic commands ###
