"""Add account deletion fields

Revision ID: 5c30b93a2a95
Revises: dabf0652c278
Create Date: 2026-06-30 06:22:08.158181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c30b93a2a95"
down_revision: Union[str, Sequence[str], None] = "dabf0652c278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("deletion_scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_deletion_attempt_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column("users", sa.Column("deletion_otp", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("deletion_otp_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deletion_otp_expires_at")
    op.drop_column("users", "deletion_otp")
    op.drop_column("users", "last_deletion_attempt_at")
    op.drop_column("users", "deletion_scheduled_at")
    # ### end Alembic commands ###
