"""add_workspace_description

Revision ID: 688e0454f8e4
Revises: 9009cade2ed8
Create Date: 2026-07-04 05:58:54.248845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "688e0454f8e4"
down_revision: Union[str, Sequence[str], None] = "9009cade2ed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "description")
    # ### end Alembic commands ###
