"""add_verification_and_task_audit

Revision ID: 8696e053fb25
Revises: a42c99a07037
Create Date: 2026-06-25 05:39:36.341673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8696e053fb25"
down_revision: Union[str, Sequence[str], None] = "a42c99a07037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_edit_histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["editor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_edit_histories_id"), "task_edit_histories", ["id"], unique=False
    )
    op.add_column("tasks", sa.Column("assignor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "tasks", "users", ["assignor_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "users",
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("verification_code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("reset_otp", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("reset_otp_expiry", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_otp_expiry")
    op.drop_column("users", "reset_otp")
    op.drop_column("users", "verification_code")
    op.drop_column("users", "is_verified")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "assignor_id")
    op.drop_index(op.f("ix_task_edit_histories_id"), table_name="task_edit_histories")
    op.drop_table("task_edit_histories")
    # ### end Alembic commands ###
