"""add_reassignment_reason_to_tasks

Revision ID: 9009cade2ed8
Revises: 9d09cade1ed7
Create Date: 2026-07-02 11:20:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9009cade2ed8"
down_revision: Union[str, Sequence[str], None] = "9d09cade1ed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("reassignment_reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "reassignment_reason")
    # ### end Alembic commands ###
