"""Add location to UserSession

Revision ID: 9d09cade1ed7
Revises: 5c30b93a2a95
Create Date: 2026-06-30 06:48:38.925786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9d09cade1ed7"
down_revision: Union[str, Sequence[str], None] = "5c30b93a2a95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_sessions", sa.Column("location", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sessions", "location")
    # ### end Alembic commands ###
