"""add_2fa_to_user

Revision ID: a69831e0be46
Revises: 8696e053fb25
Create Date: 2026-06-25 05:41:51.790829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a69831e0be46"
down_revision: Union[str, Sequence[str], None] = "8696e053fb25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "two_factor_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("two_factor_code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "two_factor_code")
    op.drop_column("users", "two_factor_enabled")
    # ### end Alembic commands ###
