"""add_membership_status_and_timestamps

Revision ID: bdeb7cc2e544
Revises: ec0239c5643c
Create Date: 2026-06-25 06:35:50.414957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bdeb7cc2e544"
down_revision: Union[str, Sequence[str], None] = "ec0239c5643c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_memberships",
        sa.Column("status", sa.String(), nullable=False, server_default="accepted"),
    )
    op.add_column(
        "workspace_memberships",
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workspace_memberships",
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_memberships", "joined_at")
    op.drop_column("workspace_memberships", "invited_at")
    op.drop_column("workspace_memberships", "status")
    # ### end Alembic commands ###
