"""add_task_due_dates_and_analytics

Revision ID: df3340643322
Revises: 04b86ed73397
Create Date: 2026-06-17 06:45:04.563523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "df3340643322"
down_revision: Union[str, Sequence[str], None] = "04b86ed73397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "due_date")
    # ### end Alembic commands ###
